apiVersion: v1
kind: ServiceAccount
metadata:
  name: gsm-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gsm-pubsub
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gsm-pubsub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gsm-pubsub
subjects:
- kind: ServiceAccount
  name: gsm-sa
